### ISSUE TITLE
Serverside crash

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/ModularUI#34]
No such crash on client.

Crash log: https://mclo.gs/fiSR5rl

Using E2E-E modpack, but modified the given modlist a bit (like, yes, replacing InvTweaks with Bogosorter).

**Comment by brachy84** [comment]
No idea what causes this

**Comment by ChromaPIE** [comment]
latest log, if it could be more helpful
https://mclo.gs/QkFxLtI

**Comment by brachy84** [comment]
Fixed on latest bogosorter commit
