### ISSUE TITLE
Opening configs with fading causing fade blink

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/ModularUI#35]
Im opening configs of Bogo Sorting mod from inside of container.

- Inside containers, background already faded.
- As i clicking [...] button, fade becomes 100% transparent and than fade in again into black

This causing unpleasant "blink".

https://github.com/CleanroomMC/ModularUI/assets/936618/2c33419c-7d8c-40dc-bd84-e60532ee76d2

**Comment by brachy84** [comment]
This is so subtle that i never noticed

**Comment by brachy84** [comment]
Fixed in latest commit
