### ISSUE TITLE
`modularui 2.3.0` Crash on game load

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/ModularUI#38]
Loading game with updated `modularui 2.3.0` causing crash:

```less
NullPointerException: Unexpected error
    at net.minecraft.client.Minecraft.handler$zgc000$timer(Minecraft.java:5337)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1094)
```

[crash-2023-11-07_11.03.40-client.txt](https://github.com/CleanroomMC/ModularUI/files/13277360/crash-2023-11-07_11.03.40-client.txt)

Downgrading to previous version fixes the issue.

**Comment by Krutoy242** [comment]
Then, please add some kind of dependency version restriction for Bogo sorting, because right now I spent half an hour to 5 times reload modpack and use binary search to find the issue source.

**Comment by brachy84** [comment]
There is. Bogo 1.4.4 only accepts modularui below 2.3.0
I have no idea why its not triggering for you

**Comment by brachy84** [comment]
You can see [here](https://github.com/CleanroomMC/InventoryBogoSorter/issues/65) that it does work
