### ISSUE TITLE
Mouse on overlay panel affect elements under panel

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/ModularUI#54]
When new panel appears, mouse still highlight items behind this panel. This looks like a bug since you cant interact with items behind current panel.

https://github.com/CleanroomMC/ModularUI/assets/936618/a72cafcc-e995-442d-ad49-c179b49110fe

**Comment by brachy84** [comment]
Version?

**Comment by Krutoy242** [comment]
Sorry, I forgot.
`modularui-2.4.2`
`bogosorter-1.4.6`
[debug.log](https://github.com/CleanroomMC/ModularUI/files/13930910/debug.log)
